title: API Documentation
description: API Documentation for various projects
theme: jekyll-theme-cayman
favicon: https://123code.net/images/favicon.png

# Google Analytics
google_analytics: # your Google Analytics tracking ID here 