title: [API]
description: Document API by phuphan đz
theme: jekyll-theme-primer
favicon: https://123code.net/images/favicon.png

# Google Analytics
google_analytics: # your Google Analytics tracking ID here 